# Set all the facts 
- name: Set facts for secret variables
  set_fact:
    secret_ghost_mail_options_auth_user: "{{ ansible_vault_ghost_mail_options_auth_user }}"
    secret_ghost_mail_options_auth_pass: "{{ ansible_vault_ghost_mail_options_auth_pass }}"
    secret_ghost_mail_options_port: "NTg3" # 587
    secret_ghost_mail_options_secure: "ZmFsc2U=" # false

# Deploy a Kubernetes Secret Service
- name: Deploy a Kubernetes Secret Service
  k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Secret
      metadata: 
        name: ghost-credentials
        namespace: "{{ ghost_namespace }}"
      type: Opaque
      data:
        ghost_mail_options_auth_user: "{{ secret_ghost_mail_options_auth_user }}"
        ghost_mail_options_auth_pass: "{{ secret_ghost_mail_options_auth_pass }}"
        ghost_mail_options_port: "{{ secret_ghost_mail_options_port }}"
        ghost_mail_options_secure: "{{ secret_ghost_mail_options_secure }}"