---
# Playbook to deploy Ghost and its components

- name: Deploy Ghost and Database on cluster
  hosts: localhost
  vars_files:
    - vars/vars.yml
  gather_facts: true
  roles:
    # setup application
    - role: secret
      when: only_dashboards == 'no'
    - role: deploy_db
      when: only_dashboards == 'no'
    - role: deploy_ghost
      when: only_dashboards == 'no'
    # setup custom dashboards for monitoring
    - role: monitoring
      when: dashboards == 'yes'