---
# Playbook to deploy Ghost and its components

- name: Deploy Ghost and Database on cluster
  hosts: localhost
  vars_files:
    - vars/vars.yml
  gather_facts: true
  roles:
      - secret
      - deploy_db
      - deploy_ghost
      #- monitoring