---
# Playbook to deploy Ghost and its components

- name: Deploy Ghost and Database on cluster
  hosts: localhost
  vars_files:
    - vars/vars.yml
  gather_facts: true
  roles:
    # setup monitoring agents (doesn't work with MacOS...)
    #- role: googlecloudplatform.google_cloud_ops_agents
    #  vars:
    #    agent_type: monitoring
    #- role: googlecloudplatform.google_cloud_ops_agents
    #  vars:
    #    agent_type: logging
    # setup application
    - secret
    - deploy_db
    - deploy_ghost
    # setup custom dashboards for monitoring
    #- monitoring