---
# Undeploy Ghost considering the variable to delete persistent data or not
- name: Undeploy Ghost
  hosts: localhost
  gather_facts: true
  tasks:
    - name: Delete all Services, Pods, Deployments and HPA from namespace 'ghost'
      shell: kubectl delete all --all -n ghost

    - name: Delete all PVC
      shell: kubectl get pvc -o name | grep "ghost" | xargs -n 1 kubectl delete;
             kubectl get pvc -o name | grep "mysql" | xargs -n 1 kubectl delete;
      when: delete_data == 'true'
    
    - name: Delete all StorageClass
      shell: kubectl delete storageclass ghost-storage;
             kubectl delete storageclass mysql-storage
      when: delete_data == 'true'

    - name: Delete ConfigMap deployed with mysql
      shell: kubectl delete configmap mysql-config
      when: delete_data == 'true'

    - name: Delete Kubernetes Secret
      shell: kubectl delete secret ghost-credentials
      when: delete_data == 'true'

    # reclaim policy for PVs is set at default (when PVC is deleted, the persistent disks are also deleted)
    # in case the policy is set to 'retain', we need to manually delete these persistent disks
    #- name: Delete Persistent Disks from Compute Engine
    #  shell: gcloud compute disks delete --quiet --region={{ gcp_region }} $(gcloud compute disks list --regions={{ gcp_region }} --filter="name:pvc*" --format="value(name)")
    #  # sometimes gcloud asks for a quick survey. if this happens, this
    #  # commands can fail because of that (it tries to delete a disk with
    #  # those lines), but it still deletes the disks. So, by ignoring these
    #  # errors, the persistent disks are still deleted and the tasks don't stop
    #  ignore_errors: true 
    #  when: delete_data == 'true'