---
# Update existing cluster with the manifests, based on regional cluster 
- name: Update existing cluster with the manifests
  shell: gcloud container clusters update ascn-cluster-1 --enable-managed-prometheus --region {{ gcp_region1 }}

- name: Scraping 

# Install the Custom Dashboard for Metric Evaluation
- name: Install the Custom Dashboard
  shell: gcloud monitoring dashboards create --config-from-file=roles/monitoring/files/custom_dashboard.json